create or replace TABLE DATAHUB.PIPELINE_METADATA.DATA_FEED_FILE_INVENTORY (
	FILE_ID NUMBER(20,0) NOT NULL COMMENT 'File_ID identifies Data_Feed_File_Inventory',
	FILE_NAME VARCHAR(100) COMMENT 'File_Name identifies Data_Feed_File_Inventory',
	FILE_NAME_PREFIX VARCHAR(100) COMMENT 'File_Nmae_prefix',
	FILE_NAME_SUFFIX VARCHAR(100) COMMENT 'File_Name_Suffix can contains the Date Timestamp',
	FILE_FORMAT VARCHAR(20) COMMENT 'File_format of the file is like CSV,DAT etc.',
	SOURCE_SYS_CODE VARCHAR(500) COMMENT 'Src_sys_Code is of Data_Feed_File_Inventory',
	FIRM_NAME VARCHAR(100) COMMENT 'Optional-Firm_Name we receive from the source. each source file can have',
	PIPELINEKEY VARCHAR(1000) COMMENT 'PilelikeKey is of Data_Feed_File_Inventory',
	SUBJECT_AREA_CODE VARCHAR(100) COMMENT 'Subject_Area_Code is of Data_Feed_File_Inventory',
	ACTIVE_FLG VARCHAR(1) COMMENT 'Active_Flag is of Data_Feed_File_Inventory',
	INBOUND_OUTBOUND_TEXT VARCHAR(10) COMMENT 'Inbound_Outbound Text has Values INBOUND/OUTBOUND',
	HEADER_AVAILABLE_FLG VARCHAR(1) COMMENT 'Header Available Flg is to identify if we have a Header in the file',
	FULL_LOAD_FLG VARCHAR(15) COMMENT 'Full_Load_Flg is of Data_Feed_File_Inventory',
	SOURCE_PRIMARY_KEY VARCHAR(1000) COMMENT 'Source Primay_key in source file',
	NOTIFY_GROUP_NAME VARCHAR(100) COMMENT 'Notify_Group_Name is the Data engineering &Sysops team to be notified',
	NOTIFY_GROUP_EMAIL VARCHAR(2000) COMMENT 'Notify_Group_email to contact if file not received from source-Data',
	DOWNSTREAM_POC_NAME VARCHAR(100) COMMENT 'Downstream_POC_Name - The Application or Business Stake holders',
	DOWNSTREAM_EMAIL VARCHAR(2000) COMMENT 'Downstream_email - The Application or Business Stake holders',
	HISTORIC_DATA_LOAD_FLG VARCHAR(1) COMMENT 'Historic_Data_Load_Flg is of Data_Feed_File_Inventory',
	COMMENTS VARCHAR(2000) COMMENT 'Comments is of Data_Feed_File_Inventory ',
	CREATED_BY_NAME VARCHAR(100) COMMENT 'Created_by_Name is of Data_Feed_File_Inventory',
	UPDATED_BY_NAME VARCHAR(100) COMMENT 'Updated_By_Name is of Data_Feed_File_Inventory',
	TARGET_DATABASE_NAME VARCHAR(300) COMMENT 'Target_Database_Name is the Database name where the Raw Table is created in Snowflake',
	TARGET_SCHEMA_NAME VARCHAR(300) COMMENT 'Target_Schema_Name is the Schema name where the Raw Table is created in Snowflake',
	TARGET_TABLE_NAME VARCHAR(300) COMMENT 'Target_Table_Name is the Table name where the Raw Table is created in Snowflake',
	STG_DATABASE_NAME VARCHAR(1000) COMMENT 'Stg_Database_Name is the Raw Database name where the file is ingested in snowflake',
	STG_SCHEMA_NAME VARCHAR(1000) COMMENT 'Stg_Schema_Name is the Raw Schema name where the file is ingested in snowflake',
	STG_TABLE_NAME VARCHAR(1000) COMMENT 'Stg_Table_Name is the Raw Table name where the file is ingested in snowflake',
	HEADER_SELECT_SCRIPT_TEXT VARCHAR(10000) COMMENT 'HEADER_SELECT_SCRIPT_TEXT script used for Temp table for deriving  info from the header',
	MULTI_LINE_FLG VARCHAR(1) COMMENT 'Does the file has multi-line format',
	NUMBER_OF_COLUMNS_COUNT NUMBER(3,0) COMMENT 'NUMBER_OF_COLUMNS_COUNT count of columns received from SQL',
	RECORD_FORMAT_LENGTH_NUMBER NUMBER(10,0) COMMENT 'RECORD_FORMAT_LENGTH_NUMBER length of each record',
	DELIMITER_CHARACTER VARCHAR(10) COMMENT 'Delimiter of the file ,|tab',
	HEADER_PATTERN_TEXT VARCHAR(100) COMMENT 'Header_Pattern_Text is the Regex pattern from the header',
	TRAILER_PATTERN_TEXT VARCHAR(100) COMMENT 'Trailer_Pattern_Text is the Regex pattern from the trailer',
	COPY_COMMAND_TEXT VARCHAR(64000) COMMENT 'COPY_COMMAND_TEXT copy command to load data to staging table',
	FILE_STORAGE_LOCATION_TEXT VARCHAR(1000) COMMENT 'file path for Azure Storage Blob',
	CREATED_TS TIMESTAMP_NTZ(9) COMMENT 'Created_TS is of Data_Feed_File_Inventory',
	UPDATED_TS TIMESTAMP_NTZ(9) COMMENT 'Updated_TS is of Data_Feed_File_Inventory',
	constraint DATA_FEED_FILE_INVENTORY_KEY primary key (FILE_ID)
);