create or replace TABLE DATAHUB.PIPELINE_METADATA.PIPELINE_RUN_AUDIT_LOG (
	PIPELINE_RUN_ID NUMBER(38,0) NOT NULL COMMENT 'RUN Id from Azure Data factory',
	PIPELINEINSTANCEID NUMBER(38,0) COMMENT 'PipelineinstanceId is FK from Pipeline_Instance',
	TASKID VARCHAR(1000) COMMENT 'TaskID is FK from Pipeline_Instance',
	PIPELINEKEY VARCHAR(500) COMMENT 'Pipeline Key FK',
	TARGET_DATABASE_NAME VARCHAR(300) COMMENT 'Target Database Name',
	TARGET_SCHEMA_NAME VARCHAR(300) COMMENT 'Target Schema',
	TARGET_TABLE_NAME VARCHAR(500) COMMENT 'Target Table Name',
	FILE_FULL_NAME VARCHAR(300) COMMENT 'Source File Name. Empty for data SQL server as source',
	ZIP_FILE_NAME VARCHAR(1000) COMMENT 'SourceZip file Name --**Path Move',
	FIRM_ID NUMBER(20,0) COMMENT 'Firm ID',
	FIRM_CODE VARCHAR(10) COMMENT 'Firm_Code The File is associated to',
	BUSINESS_DATE TIMESTAMP_NTZ(9) COMMENT 'Business_date when the event happened',
	SOURCE_FILE_EXTRACTION_TS TIMESTAMP_NTZ(9) COMMENT 'Source_File_Extraction_details the Date the file is extracted and the Filename',
	FILE_RECEIVED_TS TIMESTAMP_NTZ(9) COMMENT 'File_Received_Datetime is the data the File is reveived by OSAIC',
	TOTAL_TIME_TAKEN_IN_SECONDS_NUM NUMBER(38,0) COMMENT 'Pipeline run duration in seconds',
	FILE_SIZE_KB_NUM NUMBER(38,3) COMMENT 'File Size in KB',
	COPY_COMMAND_TEXT VARCHAR(2500) COMMENT 'Copy command from ADLS flatfile',
	REINGEST_FILE_FLAG VARCHAR(1) COMMENT 'Reingested file',
	SOURCE_FILE_ROW_COUNT NUMBER(38,0) COMMENT 'Source File Rowcount is of Pipeline_Run_Audit_Log',
	ROWS_INGESTED_COUNT NUMBER(38,0) COMMENT 'Rows_Ingested successfully',
	ROWS_FAILED_COUNT NUMBER(38,0) COMMENT 'Rows failed record count',
	LOAD_STATUS_CODE VARCHAR(30) COMMENT 'Load Status Code',
	ERROR_MESSAGE_TEXT VARCHAR(50000) COMMENT 'Error Message for running pipeline',
	ERROR_LOG_PATH_TEXT VARCHAR(2000) COMMENT 'Error Log Path',
	ELT_PROCESS_ID VARCHAR(500) COMMENT 'ETL process ID. Pileline Key and execution date.',
	ELT_EXECUTION_TS TIMESTAMP_NTZ(9) COMMENT 'ETL Pipeline exectuion date',
	ELT_CREATED_BY VARCHAR(100) COMMENT 'Created_by user or role name -service acct',
	ELT_CREATED_TS TIMESTAMP_NTZ(9) COMMENT 'ETL_Created_TS is of Pipeline_Run_Audit_log',
	ELT_RUN_STATUS VARCHAR(10) COMMENT 'Pipeline run status',
	ELT_RUN_START_TIME_TS TIMESTAMP_NTZ(9) COMMENT 'ELT_Run_Srtat_Time_TS is of Pipeline_Run_Audit_Log',
	ELT_RUN_END_TIME_TS TIMESTAMP_NTZ(9) COMMENT 'ELT_Run_End_Time_TS is of Pipeline_Run_Audit_Log',
	STG_DATABASE_NAME VARCHAR(1000) COMMENT 'Stage Database Name',
	STG_SCHEMA_NAME VARCHAR(1000) COMMENT 'Stage Schema Name',
	STG_TABLE_NAME VARCHAR(1000) COMMENT 'Stage Table Name',
	constraint PIPELINE_RUN_AUDIT_LOG_KEY primary key (PIPELINE_RUN_ID)
);