// SYS_QA_FP_ELT_RW
USE ROLE AZ_AD_SNOWFLAKE_FR_SYS_QA_FP_ELT_ADMIN;
GRANT USAGE, MODIFY, MONITOR, CREATE SCHEMA ON DATABASE QA_FP_FP TO ROLE SYS_QA_FP_ELT_RW;

GRANT USAGE, MODIFY, MONITOR, CREATE ON SCHEMA QA_FP_FP.ELT_STAGE TO ROLE SYS_QA_FP_ELT_RW;
GRANT USAGE, MODIFY, MONITOR, CREATE ON SCHEMA QA_FP_FP.FINRA TO ROLE SYS_QA_FP_ELT_RW;
GRANT USAGE, MODIFY, MONITOR, CREATE ON SCHEMA QA_FP_FP.FINRA_RAW TO ROLE SYS_QA_FP_ELT_RW;
GRANT USAGE, MODIFY, MONITOR, CREATE ON SCHEMA QA_FP_FP.LR TO ROLE SYS_QA_FP_ELT_RW;
GRANT USAGE, MODIFY, MONITOR, CREATE ON SCHEMA QA_FP_FP.LR_RAW TO ROLE SYS_QA_FP_ELT_RW;
GRANT USAGE, MODIFY, MONITOR, CREATE ON SCHEMA QA_FP_FP.MIPS TO ROLE SYS_QA_FP_ELT_RW;
GRANT USAGE, MODIFY, MONITOR, CREATE ON SCHEMA QA_FP_FP.MIPS_RAW TO ROLE SYS_QA_FP_ELT_RW;
GRANT USAGE, MODIFY, MONITOR, CREATE ON SCHEMA QA_FP_FP.SF TO ROLE SYS_QA_FP_ELT_RW;
GRANT USAGE, MODIFY, MONITOR, CREATE ON SCHEMA QA_FP_FP.SF_RAW TO ROLE SYS_QA_FP_ELT_RW;
GRANT USAGE, MODIFY, MONITOR, CREATE ON SCHEMA QA_FP_FP.LOGS TO ROLE SYS_QA_FP_ELT_RW;
GRANT USAGE, MODIFY, MONITOR, CREATE ON SCHEMA QA_FP_FP.EDIP TO ROLE SYS_QA_FP_ELT_RW;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA QA_FP_FP.ELT_STAGE TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA QA_FP_FP.FINRA TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA QA_FP_FP.LR TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA QA_FP_FP.LR_RAW TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA QA_FP_FP.MIPS TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA QA_FP_FP.SF TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA QA_FP_FP.SF_RAW TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA QA_FP_FP.LOGS TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.EDIP TO ROLE SYS_QA_FP_ELT_RW;

GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.ELT_STAGE TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.FINRA TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LR TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LR_RAW TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.MIPS TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.SF TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.SF_RAW TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LOGS TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.EDIP TO ROLE SYS_QA_FP_ELT_RW;

--Future permissions
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE QA_FP_FP TO ROLE SYS_QA_FP_ELT_RW;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.ELT_STAGE TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.FINRA TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.LR TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.LR_RAW TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.MIPS TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.SF TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.SF_RAW TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.LOGS TO ROLE SYS_QA_FP_ELT_RW;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.EDIP TO ROLE SYS_QA_FP_ELT_RW;


// SYS_QA_FP_ELT_RO
USE ROLE AZ_AD_SNOWFLAKE_FR_SYS_QA_FP_ELT_ADMIN;
GRANT USAGE ON DATABASE QA_FP_FP TO ROLE SYS_QA_FP_ELT_RO;

GRANT USAGE ON SCHEMA QA_FP_FP.ELT_STAGE TO ROLE SYS_QA_FP_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.FINRA TO ROLE SYS_QA_FP_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.FINRA_RAW TO ROLE SYS_QA_FP_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.LR TO ROLE SYS_QA_FP_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.LR_RAW TO ROLE SYS_QA_FP_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.MIPS TO ROLE SYS_QA_FP_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.MIPS_RAW TO ROLE SYS_QA_FP_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.SF TO ROLE SYS_QA_FP_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.SF_RAW TO ROLE SYS_QA_FP_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.LOGS TO ROLE SYS_QA_FP_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.EDIP TO ROLE SYS_QA_FP_ELT_RO;

GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.ELT_STAGE TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.FINRA TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.LR TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.LR_RAW TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.MIPS TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.SF TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.SF_RAW TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.LOGS TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.EDIP TO ROLE SYS_QA_FP_ELT_RO;

GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.ELT_STAGE TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.FINRA TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LR TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LR_RAW TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.MIPS TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.SF TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.SF_RAW TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LOGS TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.EDIP TO ROLE SYS_QA_FP_ELT_RO;

--Future permissions
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE QA_FP_FP TO ROLE SYS_QA_FP_ELT_RO;

GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.ELT_STAGE TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.FINRA TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.LR TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.LR_RAW TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.MIPS TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.SF TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.SF_RAW TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.LOGS TO ROLE SYS_QA_FP_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.EDIP TO ROLE SYS_QA_FP_ELT_RO;


// SYS_QA_FP_RO_RAW
USE ROLE AZ_AD_SNOWFLAKE_FR_SYS_QA_FP_ELT_ADMIN;
GRANT USAGE ON DATABASE QA_FP_FP TO ROLE SYS_QA_FP_RO_RAW;

GRANT USAGE ON SCHEMA QA_FP_FP.FINRA_RAW TO ROLE SYS_QA_FP_RO_RAW;
GRANT USAGE ON SCHEMA QA_FP_FP.LR_RAW TO ROLE SYS_QA_FP_RO_RAW;
GRANT USAGE ON SCHEMA QA_FP_FP.MIPS_RAW TO ROLE SYS_QA_FP_RO_RAW;
GRANT USAGE ON SCHEMA QA_FP_FP.SF_RAW TO ROLE SYS_QA_FP_RO_RAW;

GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE SYS_QA_FP_RO_RAW;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.LR_RAW TO ROLE SYS_QA_FP_RO_RAW;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE SYS_QA_FP_RO_RAW;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.SF_RAW TO ROLE SYS_QA_FP_RO_RAW;

GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE SYS_QA_FP_RO_RAW;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LR_RAW TO ROLE SYS_QA_FP_RO_RAW;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE SYS_QA_FP_RO_RAW;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.SF_RAW TO ROLE SYS_QA_FP_RO_RAW;

--Future permissions
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE QA_FP_FP TO ROLE SYS_QA_FP_RO_RAW;

GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE SYS_QA_FP_RO_RAW;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.LR_RAW TO ROLE SYS_QA_FP_RO_RAW;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE SYS_QA_FP_RO_RAW;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.SF_RAW TO ROLE SYS_QA_FP_RO_RAW;


// USR_QA_FP_FP_RW 
USE ROLE AZ_AD_SNOWFLAKE_FR_USR_QA_FP_DBA;
GRANT USAGE ON DATABASE QA_FP_FP TO ROLE USR_QA_FP_FP_RW; 

GRANT USAGE ON SCHEMA QA_FP_FP.ELT_STAGE TO ROLE USR_QA_FP_FP_RW; 
GRANT USAGE ON SCHEMA QA_FP_FP.FINRA TO ROLE USR_QA_FP_FP_RW; 
GRANT USAGE ON SCHEMA QA_FP_FP.FINRA_RAW TO ROLE USR_QA_FP_FP_RW; 
GRANT USAGE ON SCHEMA QA_FP_FP.LR TO ROLE USR_QA_FP_FP_RW; 
GRANT USAGE ON SCHEMA QA_FP_FP.LR_RAW TO ROLE USR_QA_FP_FP_RW; 
GRANT USAGE ON SCHEMA QA_FP_FP.MIPS TO ROLE USR_QA_FP_FP_RW; 
GRANT USAGE ON SCHEMA QA_FP_FP.MIPS_RAW TO ROLE USR_QA_FP_FP_RW; 
GRANT USAGE ON SCHEMA QA_FP_FP.SF TO ROLE USR_QA_FP_FP_RW; 
GRANT USAGE ON SCHEMA QA_FP_FP.SF_RAW TO ROLE USR_QA_FP_FP_RW; 
GRANT USAGE ON SCHEMA QA_FP_FP.LOGS TO ROLE USR_QA_FP_FP_RW; 
GRANT USAGE ON SCHEMA QA_FP_FP.EDIP TO ROLE USR_QA_FP_FP_RW; 

GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA QA_FP_FP.ELT_STAGE TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA QA_FP_FP.FINRA TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA QA_FP_FP.LR TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA QA_FP_FP.LR_RAW TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA QA_FP_FP.MIPS TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA QA_FP_FP.SF TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA QA_FP_FP.SF_RAW TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA QA_FP_FP.LOGS TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA QA_FP_FP.EDIP TO ROLE USR_QA_FP_FP_RW; 

GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.ELT_STAGE TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.FINRA TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LR TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LR_RAW TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.MIPS TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.SF TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.SF_RAW TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LOGS TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.EDIP TO ROLE USR_QA_FP_FP_RW; 

--Future permissions
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE QA_FP_FP TO ROLE USR_QA_FP_FP_RW; 

GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.ELT_STAGE TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.FINRA TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.LR TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.LR_RAW TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.MIPS TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.SF TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.SF_RAW TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.LOGS TO ROLE USR_QA_FP_FP_RW; 
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA QA_FP_FP.EDIP TO ROLE USR_QA_FP_FP_RW; 


// USR_QA_FP_FP_NO_ELT_RO
USE ROLE AZ_AD_SNOWFLAKE_FR_USR_QA_FP_DBA;

GRANT USAGE ON DATABASE QA_FP_FP TO ROLE USR_QA_FP_FP_NO_ELT_RO;

GRANT USAGE ON SCHEMA QA_FP_FP.FINRA TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.FINRA_RAW TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.LR TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.LR_RAW TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.MIPS TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.MIPS_RAW TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.SF TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.SF_RAW TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.LOGS TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.EDIP TO ROLE USR_QA_FP_FP_NO_ELT_RO;

GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.FINRA TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.LR TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.LR_RAW TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.MIPS TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.SF TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.SF_RAW TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.LOGS TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.EDIP TO ROLE USR_QA_FP_FP_NO_ELT_RO;

GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.FINRA TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LR TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LR_RAW TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.MIPS TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.SF TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.SF_RAW TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LOGS TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.EDIP TO ROLE USR_QA_FP_FP_NO_ELT_RO;

--Future permissions
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE QA_FP_FP TO ROLE USR_QA_FP_FP_NO_ELT_RO;

GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.FINRA TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.LR TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.LR_RAW TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.MIPS TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.SF TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.SF_RAW TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.LOGS TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.EDIP TO ROLE USR_QA_FP_FP_NO_ELT_RO;

// USR_QA_FP_FP_CURATED_RO
USE ROLE AZ_AD_SNOWFLAKE_FR_USR_QA_FP_DBA;

GRANT USAGE ON DATABASE QA_FP_FP TO ROLE USR_QA_FP_FP_CURATED_RO;

GRANT USAGE ON SCHEMA QA_FP_FP.FINRA TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.LR TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.MIPS TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.SF TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.LOGS TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.EDIP TO ROLE USR_QA_FP_FP_CURATED_RO;

GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.FINRA TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.LR TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.MIPS TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.SF TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.LOGS TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.EDIP TO ROLE USR_QA_FP_FP_CURATED_RO;

GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.FINRA TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LR TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.MIPS TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.SF TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LOGS TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.EDIP TO ROLE USR_QA_FP_FP_CURATED_RO;

--Future permissions
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE QA_FP_FP TO ROLE USR_QA_FP_FP_CURATED_RO;

GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.FINRA TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.LR TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.MIPS TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.SF TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.LOGS TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.EDIP TO ROLE USR_QA_FP_FP_CURATED_RO;


// USR_QA_FP_FP_RO
USE ROLE AZ_AD_SNOWFLAKE_FR_USR_QA_FP_DBA;

GRANT USAGE ON DATABASE QA_FP_FP TO ROLE USR_QA_FP_FP_RO;

GRANT USAGE ON SCHEMA QA_FP_FP.ELT_STAGE TO ROLE USR_QA_FP_FP_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.FINRA TO ROLE USR_QA_FP_FP_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.FINRA_RAW TO ROLE USR_QA_FP_FP_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.LR TO ROLE USR_QA_FP_FP_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.LR_RAW TO ROLE USR_QA_FP_FP_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.MIPS TO ROLE USR_QA_FP_FP_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.MIPS_RAW TO ROLE USR_QA_FP_FP_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.SF TO ROLE USR_QA_FP_FP_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.SF_RAW TO ROLE USR_QA_FP_FP_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.LOGS TO ROLE USR_QA_FP_FP_RO;
GRANT USAGE ON SCHEMA QA_FP_FP.EDIP TO ROLE USR_QA_FP_FP_RO;

GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.ELT_STAGE TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.FINRA TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.LR TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.LR_RAW TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.MIPS TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.SF TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.SF_RAW TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.LOGS TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA QA_FP_FP.EDIP TO ROLE USR_QA_FP_FP_RO;

GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.ELT_STAGE TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.FINRA TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LR TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LR_RAW TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.MIPS TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.SF TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.SF_RAW TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.LOGS TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA QA_FP_FP.EDIP TO ROLE USR_QA_FP_FP_RO;

--Future permissions
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE QA_FP_FP TO ROLE USR_QA_FP_FP_RO;

GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.ELT_STAGE TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.FINRA TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.FINRA_RAW TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.LR TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.LR_RAW TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.MIPS TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.MIPS_RAW TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.SF TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.SF_RAW TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.LOGS TO ROLE USR_QA_FP_FP_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QA_FP_FP.EDIP TO ROLE USR_QA_FP_FP_RO;



//Warehouse options

//WH Specific QA Access Roles
USE ROLE AZ_AD_SNOWFLAKE_FR_SYS_QA_FP_ELT_ADMIN;
GRANT MODIFY, MONITOR, USAGE, OPERATE ON WAREHOUSE QA_FP_RAW_WH TO ROLE SYS_QA_FP_WH;
GRANT MODIFY, MONITOR, USAGE, OPERATE ON WAREHOUSE QA_FP_CURATED_WH TO ROLE SYS_QA_FP_WH;
GRANT MODIFY, MONITOR, USAGE, OPERATE ON WAREHOUSE QA_FP_ANALYZE_WH TO ROLE SYS_QA_FP_WH;
GRANT MODIFY, MONITOR, USAGE, OPERATE ON WAREHOUSE QA_FP_REPORT_WH TO ROLE SYS_QA_FP_WH;

USE ROLE AZ_AD_SNOWFLAKE_FR_USR_QA_FP_DBA;
GRANT MODIFY, MONITOR, USAGE, OPERATE ON WAREHOUSE QA_FP_RAW_WH TO ROLE USR_QA_FP_WH;
GRANT MODIFY, MONITOR, USAGE, OPERATE ON WAREHOUSE QA_FP_CURATED_WH ROLE USR_QA_FP_WH;
GRANT MODIFY, MONITOR, USAGE, OPERATE ON WAREHOUSE QA_FP_ANALYZE_WH ROLE USR_QA_FP_WH;
GRANT MODIFY, MONITOR, USAGE, OPERATE ON WAREHOUSE QA_FP_REPORT_WH ROLE USR_QA_FP_WH;

//Access to WH by Access Role
USE ROLE AZ_AD_SNOWFLAKE_FR_SYS_QA_FP_ELT_ADMIN;

GRANT OPERATE ON WAREHOUSE QA_FP_RAW_WH TO ROLE SYS_QA_FP_ELT_RW;
GRANT OPERATE ON WAREHOUSE QA_FP_CURATED_WH TO ROLE SYS_QA_FP_ELT_RW;
GRANT OPERATE ON WAREHOUSE QA_FP_ANALYZE_WH TO ROLE SYS_QA_FP_ELT_RW;
GRANT OPERATE ON WAREHOUSE QA_FP_REPORT_WH TO ROLE SYS_QA_FP_ELT_RW;

GRANT OPERATE ON WAREHOUSE QA_FP_RAW_WH TO ROLE SYS_QA_FP_ELT_RO;
GRANT OPERATE ON WAREHOUSE QA_FP_CURATED_WH TO ROLE SYS_QA_FP_ELT_RO;
GRANT OPERATE ON WAREHOUSE QA_FP_ANALYZE_WH TO ROLE SYS_QA_FP_ELT_RO;
GRANT OPERATE ON WAREHOUSE QA_FP_REPORT_WH TO ROLE SYS_QA_FP_ELT_RO;

GRANT OPERATE ON WAREHOUSE QA_FP_RAW_WH TO ROLE SYS_QA_FP_RO_RAW;


USE ROLE AZ_AD_SNOWFLAKE_FR_USR_QA_FP_DBA;

GRANT OPERATE ON WAREHOUSE QA_FP_RAW_WH TO ROLE USR_QA_FP_FP_RW; 
GRANT OPERATE ON WAREHOUSE QA_FP_CURATED_WH TO ROLE USR_QA_FP_FP_RW; 

GRANT OPERATE ON WAREHOUSE QA_FP_CURATED_WH TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT OPERATE ON WAREHOUSE QA_FP_ANALYZE_WH TO ROLE USR_QA_FP_FP_CURATED_RO;
GRANT OPERATE ON WAREHOUSE QA_FP_REPORT_WH TO ROLE USR_QA_FP_FP_CURATED_RO;

GRANT OPERATE ON WAREHOUSE QA_FP_RAW_WH TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT OPERATE ON WAREHOUSE QA_FP_CURATED_WH TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT OPERATE ON WAREHOUSE QA_FP_ANALYZE_WH TO ROLE USR_QA_FP_FP_NO_ELT_RO;
GRANT OPERATE ON WAREHOUSE QA_FP_REPORT_WH TO ROLE USR_QA_FP_FP_NO_ELT_RO;

GRANT OPERATE ON WAREHOUSE QA_FP_REPORT_WH TO ROLE USR_QA_FP_FP_RO;

