// Maping the functional roles to access roles for FP
GRANT ROLE SYS_QA_FP_ELT_RW TO AZ_APP_AD_SNOWFLAKE_FR_SYS_QA_FP_ELT_ADMIN;
GRANT ROLE SYS_QA_FP_ELT_RO TO AZ_APP_AD_SNOWFLAKE_FR_SYS_QA_FP_ELT_ADMIN;
GRANT ROLE SYS_QA_FP_WH TO AZ_APP_AD_SNOWFLAKE_FR_SYS_QA_FP_ELT_ADMIN;
GRANT ROLE SYS_QA_FP_RO_RAW TO AZ_APP_AD_SNOWFLAKE_FR_SYS_QA_FP_ELT_ADMIN;

GRANT ROLE USR_QA_FP_RW TO AZ_APP_AD_SNOWFLAKE_FR_USR_QA_FP_DBA;
GRANT ROLE USR_QA_FP_WH TO AZ_APP_AD_SNOWFLAKE_FR_USR_QA_FP_DBA;
GRANT ROLE USR_QA_FP_CURATED_RO TO AZ_APP_AD_SNOWFLAKE_FR_USR_QA_FP_DBA;
GRANT ROLE USR_QA_FP_NO_ELT_RO TO AZ_APP_AD_SNOWFLAKE_FR_USR_QA_FP_DBA;
GRANT ROLE USR_QA_FP_RO TO AZ_APP_AD_SNOWFLAKE_FR_USR_QA_FP_DBA;
