# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(SourceBranchName)_$(Build_Pipeline)_$(date:yyyyMMdd)$(rev:.r)

trigger:
- master

pool:
  name: Default

steps:

- script: |
    echo ""
    echo "System.TeamProject: $(System.TeamProject)"
    echo "Build.Repository.Name: $(Build.Repository.Name)"
    echo "Build.BuildId: $(Build.BuildId)"
    echo "Build.BuildNumber: $(Build.BuildNumber)"
    echo ""
    echo "Agent.BuildDirectory: $(Agent.BuildDirectory)"
    echo "Build.ArtifactStagingDirectory: $(Build.ArtifactStagingDirectory)"
    echo "Build.BinariesDirectory: $(Build.BinariesDirectory)"
    echo "Build.SourcesDirectory: $(Build.SourcesDirectory)"
    echo ""
    echo "Initial Structure of BuildDirectory folder of this pipeline: find $(Agent.BuildDirectory) -print | sed -e <QUOTE>s;[^/]*/;|____;g;s;____|; |;g<QUOTE>"
  displayName: 'Check Initial Structure of BuildDirectory folder'


- task: CopyFiles@2
  displayName: "Copy Code Files"
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      src/**
      dags/**
      drivers/**
      config/**
      saviynt/**
      Pipfile
      Pipfile.lock
    TargetFolder: '$(Build.ArtifactStagingDirectory)/s'
    CleanTargetFolder: true
    OverWrite: true


- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/s'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name)_$(Build.buildNumber).zip'
    replaceExistingArchive: true


#- task: Veracode@3
#  inputs:
#    ConnectionDetailsSelection: 'Endpoint'
#    AnalysisService: 'DA Veracode'
#    veracodeAppProfile: 'EDIP-Code'
#    version: '$(Build.Repository.Name)_$(build.buildNumber)'
#    filepath: '$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name)_$(Build.buildNumber).zip'



- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(build.artifactstagingdirectory)/s/src
    artifactName: SRC
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(build.artifactstagingdirectory)/s/dags
    artifactName: DAGS
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(build.artifactstagingdirectory)/s/drivers
    artifactName: DRIVERS
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(build.artifactstagingdirectory)/s/config
    artifactName: CONFIG
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(build.artifactstagingdirectory)/s/saviynt
    artifactName: SAVIYNT


- script: |
    echo ""
    echo "Final Structure of BuildDirectory folder of this pipeline: find $(Agent.BuildDirectory) -print | sed -e <QUOTE>s;[^/]*/;|____;g;s;____|; |;g<QUOTE>"
  displayName: 'Check Final Structure of BuildDirectory folder'
