CREATE VIEW [dbo].[envestnet_wmp_access_controls] AS
SELECT
    B.BRANCH_CODE,
    A.RECORD_TYPE AS ADVISOR_RECORD_TYPE,
    A.ADVISOR_ID,
    A.FIRST_NAME_PII AS ADVISOR_FIRST_NAME,
    A.MIDDLE_NAME_PII AS ADVISOR_MIDDLE_NAME,
    A.LAST_NAME_PII AS ADVISOR_LAST_NAME, 
    A.REP_CODE,
    A.USER_NAME_PII AS USER_NAME,
    T.ENTERPRISE_ID,
    T.ENTERPRISE_NAME,
    F.FIRM_ID,
    F.FIRM_SHORT_NAME, 
    F.FIRM_NAME, 
    B.BRANCH_ID,
    E.ENTITLEMENT, 
    E.ENTITLEMENT_VALUE,
    A.MANAGER_REP_CODE,
    A.SSN_NUMBER_PII AS SSN_NUMBER,
    A.DATE_OF_BIRTH_PII AS ADVISOR_DATE_OF_BIRTH,
    A.CRD_NUMBER,
    A.DBA_NAME,
    A.START_DATE,
    A.TERMINATION_DATE,
    A.TERMINATION_REASON,
    CASE WHEN ISNULL(A.TERMINATION_DATE,'')='' THEN 'ACTIVE' ELSE 'INACTIVE' END AS ACCOUNT_STATUS,
    A.HOME_STATE,
    A.SSO_USER_NAME_PII AS SSO_USER_NAME,
    A.ALTERNATE_SSO_USER_NAME_PII AS ALTERNATE_SSO_USER_NAME,
    A.SELECTED_ADVISORS,
    A.ADVISOR_STATUS,
    A.RECORD_TYPE, 
    A.ADVISOR_CODE,
    A.ADVISOR_ID AS OWNER_ID,
    O.OWNER_TYPE_ID,
    O.OWNER_TYPE_NAME
FROM
    dbo.ENVESTNET_HIERARCHY_ENTERPRISE T
    LEFT JOIN dbo.ENVESTNET_HIERARCHY_FIRM F ON F.ENTERPRISE_ID = T.ENTERPRISE_ID AND F.META_IS_CURRENT = 1
    LEFT JOIN dbo.ENVESTNET_HIERARCHY_BRANCH B ON B.ENTERPRISE_ID = T.ENTERPRISE_ID AND B.FIRM_ID = F.FIRM_ID AND B.META_IS_CURRENT = 1
    LEFT JOIN dbo.ENVESTNET_HIERARCHY_ADVISOR A ON A.ENTERPRISE_ID = T.ENTERPRISE_ID AND A.BRANCH_ID = B.BRANCH_ID AND A.FIRM_ID = B.FIRM_ID AND A.META_IS_CURRENT = 1
    LEFT JOIN dbo.ENVESTNET_HIERARCHY_CONTACT C ON C.OWNER_ID = A.ADVISOR_ID AND C.OWNER_TYPE_ID = '2' AND C.META_IS_CURRENT = 1
    LEFT JOIN dbo.ENVESTNET_HIERARCHY_ENTITLEMENT E ON E.OWNER_ID = A.ADVISOR_ID AND E.META_IS_CURRENT = 1
    LEFT JOIN dbo.ENVESTNET_CODES_OWNER_TYPE O ON O.OWNER_TYPE_ID = C.OWNER_TYPE_ID AND O.META_IS_CURRENT = 1
WHERE 1=1
    AND T.META_IS_CURRENT = 1
    AND F.FIRM_ID NOT IN ('22', '19', '18', '20')
    AND B.BRANCH_ID IN ('127', '8981')
--ORDER BY FIRM_NAME, A.LAST_NAME_PII, A.FIRST_NAME_PII
;
