CREATE VIEW [dbo].[pershing_spat_e] AS
SELECT
    [header_name],
    [header_firm_name],
    [header_remote_id],
    [header_refreshed_updated],
    [header_run_date],
    [header_run_time],
    [transaction_code],
    [record_identifier],
    [record_id_sequence_number],
    [user_id],
    [introducing_broker_dealer_ibd_number],
    [user_first_name],
    [user_last_name],
    [id_creation_date],
    [effective_start_date_of_user_job_content_entitlement],
    [effective_end_date_of_user_content_entitlement],
    [job_function_entitlement_status_code],
    [user_id_of_administrator],
    [user_job_function_entitlement_update_date],
    [for_pershing_internal_use_only],
    [job_function_entitlement_name],
    [job_function_entitlement_description],
    [template_owner],
    [job_function_template_alternate_key_id],
    [introducing_firm],
    [introducing_firm_context_enabled_indicator],
    [context_entitlement_name],
    [meta_pipeline_key],
    [meta_is_full_load],
    [meta_run_date],
    [meta_date_of_data],
    [meta_start_date],
    [meta_end_date],
    [meta_is_current],
    [meta_hash_key]
FROM [dbo].[pershing_raa_spat_e] WHERE [meta_is_current] = 1
UNION ALL
SELECT
    [header_name],
    [header_firm_name],
    [header_remote_id],
    [header_refreshed_updated],
    [header_run_date],
    [header_run_time],
    [transaction_code],
    [record_identifier],
    [record_id_sequence_number],
    [user_id],
    [introducing_broker_dealer_ibd_number],
    [user_first_name],
    [user_last_name],
    [id_creation_date],
    [effective_start_date_of_user_job_content_entitlement],
    [effective_end_date_of_user_content_entitlement],
    [job_function_entitlement_status_code],
    [user_id_of_administrator],
    [user_job_function_entitlement_update_date],
    [for_pershing_internal_use_only],
    [job_function_entitlement_name],
    [job_function_entitlement_description],
    [template_owner],
    [job_function_template_alternate_key_id],
    [introducing_firm],
    [introducing_firm_context_enabled_indicator],
    [context_entitlement_name],
    [meta_pipeline_key],
    [meta_is_full_load],
    [meta_run_date],
    [meta_date_of_data],
    [meta_start_date],
    [meta_end_date],
    [meta_is_current],
    [meta_hash_key]
FROM [dbo].[pershing_sai_spat_e] WHERE [meta_is_current] = 1
;



CREATE VIEW [dbo].[pershing_spat_j] AS
SELECT
    [header_name],
    [header_firm_name],
    [header_remote_id],
    [header_refreshed_updated],
    [header_run_date],
    [header_run_time],
    [transaction_code],
    [record_identifier],
    [record_id_sequence_number],
    [for_pershing_internal_use_only],
    [introducing_broker_dealer_ibd_number],
    [job_function_name],
    [effective_start_date_of_job_function],
    [effective_end_date_of_user_content_entitlement],
    [job_function_create_or_update_date],
    [user_id_of_administrator],
    [category_name],
    [id_unique_bfe_identifier],
    [bfe_name],
    [bfe_access_level],
    [bfe_description],
    [template_owner],
    [job_function_template_alternate_key_id],
    [introducing_firm],
    [introducing_firm_context_enabled_indicator],
    [context_entitlement_name],
    [meta_pipeline_key],
    [meta_is_full_load],
    [meta_run_date],
    [meta_date_of_data],
    [meta_start_date],
    [meta_end_date],
    [meta_is_current],
    [meta_hash_key]
FROM [dbo].[pershing_raa_spat_j] WHERE [meta_is_current] = 1
UNION ALL
SELECT
    [header_name],
    [header_firm_name],
    [header_remote_id],
    [header_refreshed_updated],
    [header_run_date],
    [header_run_time],
    [transaction_code],
    [record_identifier],
    [record_id_sequence_number],
    [for_pershing_internal_use_only],
    [introducing_broker_dealer_ibd_number],
    [job_function_name],
    [effective_start_date_of_job_function],
    [effective_end_date_of_user_content_entitlement],
    [job_function_create_or_update_date],
    [user_id_of_administrator],
    [category_name],
    [id_unique_bfe_identifier],
    [bfe_name],
    [bfe_access_level],
    [bfe_description],
    [template_owner],
    [job_function_template_alternate_key_id],
    [introducing_firm],
    [introducing_firm_context_enabled_indicator],
    [context_entitlement_name],
    [meta_pipeline_key],
    [meta_is_full_load],
    [meta_run_date],
    [meta_date_of_data],
    [meta_start_date],
    [meta_end_date],
    [meta_is_current],
    [meta_hash_key]
FROM [dbo].[pershing_sai_spat_j] WHERE [meta_is_current] = 1
;



CREATE VIEW [dbo].[pershing_spat_m] AS
SELECT
    [header_name],
    [header_firm_name],
    [header_remote_id],
    [header_refreshed_updated],
    [header_run_date],
    [header_run_time],
    [transaction_code],
    [record_identifier],
    [record_id_sequence_number],
    [user_id],
    [introducing_broker_dealer_ibd_number],
    [user_first_name],
    [user_last_name],
    [id_creation_date],
    [effective_start_of_date_profile],
    [end_date_of_data_profile],
    [data_profile_update_status_code],
    [user_id_of_administrator],
    [user_content_entitlement_update_date],
    [data_profile_id],
    [data_profile_name],
    [data_profile_description],
    [introducing_firm],
    [introducing_firm_context_enabled_indicator],
    [context_entitlement_name],
    [meta_pipeline_key],
    [meta_is_full_load],
    [meta_run_date],
    [meta_date_of_data],
    [meta_start_date],
    [meta_end_date],
    [meta_is_current],
    [meta_hash_key]
FROM [dbo].[pershing_raa_spat_m] WHERE [meta_is_current] = 1
UNION ALL
SELECT
    [header_name],
    [header_firm_name],
    [header_remote_id],
    [header_refreshed_updated],
    [header_run_date],
    [header_run_time],
    [transaction_code],
    [record_identifier],
    [record_id_sequence_number],
    [user_id],
    [introducing_broker_dealer_ibd_number],
    [user_first_name],
    [user_last_name],
    [id_creation_date],
    [effective_start_of_date_profile],
    [end_date_of_data_profile],
    [data_profile_update_status_code],
    [user_id_of_administrator],
    [user_content_entitlement_update_date],
    [data_profile_id],
    [data_profile_name],
    [data_profile_description],
    [introducing_firm],
    [introducing_firm_context_enabled_indicator],
    [context_entitlement_name],
    [meta_pipeline_key],
    [meta_is_full_load],
    [meta_run_date],
    [meta_date_of_data],
    [meta_start_date],
    [meta_end_date],
    [meta_is_current],
    [meta_hash_key]
FROM [dbo].[pershing_sai_spat_m] WHERE [meta_is_current] = 1
;



CREATE VIEW [dbo].[pershing_netx360_backoffice_user_identity] AS
SELECT
e.header_firm_name,
e.header_remote_id,
e.introducing_broker_dealer_ibd_number,
e.user_id,
e.user_id_of_administrator,
e.user_first_name,
e.user_last_name,
e.id_creation_date,
e.effective_start_date_of_user_job_content_entitlement,
e.effective_end_date_of_user_content_entitlement,
e.job_function_entitlement_status_code,
e.job_function_entitlement_name,
e.job_function_entitlement_description,
j.job_function_name,
e.template_owner,
e.job_function_template_alternate_key_id,
j.category_name,
j.id_unique_bfe_identifier,
j.bfe_name,
j.bfe_access_level,
j.bfe_description
FROM [dbo].[pershing_spat_e] E
INNER JOIN [dbo].[pershing_spat_J] J
	ON j.job_function_template_alternate_key_id = e.job_function_template_alternate_key_id
	AND j.header_remote_id = e.header_remote_id
WHERE E.job_function_entitlement_name = 'HOME OFFICE V2020 TEMPLATE'
;



