environment: QA



output_log_path: /usr/local/spark/resources/fileshare/Shared/logs
output_cicd_path: /usr/local/spark/resources/fileshare/Shared/CICD
create_cicd_file: true



azure_storage_accounts_prefix: ag
azure_storage_accounts_default_mid: aggr
azure_storage_accounts_suffix: lakescd



data_paths_per_source:
    # Financial Professional:
    FINRA: /usr/local/spark/resources/fileshare/Shared/FINRA
    LR: /usr/local/spark/resources/fileshare/Shared/LR
    MIPS: /usr/local/spark/resources/fileshare/Shared/MIPS
    SF: /usr/local/spark/resources/fileshare/Shared/SF

    # Client and Account:
    PERSHING: /usr/local/spark/resources/fileshare/Shared/PERSHING




temporary_file_path: /usr/local/spark/resources/Shared/TEMP



copy_history_log_databases: 
    - FP
    - CA



snowflake_account: advisorgroup-edip
snowflake_key_vault_account: snowflake
snowflake_role: AD_SNOWFLAKE_QA_DBA
snowflake_warehouse: QA_RAW_WH



lr_sql_server: TSQLOLTP01
lr_sql_key_vault_account: TSQLOLTP01



reverse_etl_sql_server: DW1SQLOLTP02
reverse_etl_sql_key_vault_account: DSQLOLTP02

reverse_etl_map:
    FP:
        snowflake_schema: EDIP
        sql_database: FinancialProfessional
        sql_schema: sfexport



file_history_sql_server: DW1SQLOLTP02
file_history_sql_key_vault_account: sqledipingestion
file_history_sql_database: EDIPIngestion
file_history_sql_schema: edip



vacuuming_days_to_retain: 7



salesforce_api_version: "40.0"
triad_salesforce_key_vault_account: salesforce
triad_salesforce_host: triadadvisors.my.salesforce.com
is_triad_salesforce_sandbox: false



file_history_start_date:
    FINRA: "2021-08-15"
    PERSHING: "2021-08-15"



