CREATE OR REPLACE PROCEDURE DATAHUB.PIPELINE_METADATA.SP_CREATE_STAGE_BRONZE_SILVER_TABLE_OBJECTS("FILE_ID" NUMBER(38,0), "FILE_TYPE" VARCHAR, "FILE_FORMAT_NAME" VARCHAR, "SKIP_HEADER" VARCHAR, "ADDITIONAL_WHERE_CONDITIONS" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
CALL POPULATE_INGESTION_TABLE_DETAILS(:FILE_ID,:FILE_TYPE);
CALL DATAHUB.PIPELINE_METADATA.SP_CREATE_STAGE_BRONZE_TABLE(:FILE_ID,:FILE_TYPE);
CALL DATAHUB.PIPELINE_METADATA.SP_CREATE_COPY_COMMAND(:FILE_ID,:FILE_FORMAT_NAME,:SKIP_HEADER,:ADDITIONAL_WHERE_CONDITIONS);
END';