CREATE OR REPLACE PROCEDURE DATAHUB.PIPELINE_METADATA.SP_CREATE_COPY_COMMAND("FILE_ID" NUMBER(38,0), "FILE_FORMAT_NAME" VARCHAR, "SKIP_HEADER" VARCHAR, "ADDITIONAL_WHERE_CONDITIONS" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE 
	COPY_COMMAND STRING;
	STAGE_TABLE_DETAIL STRING;
	FILE_FORMAT STRING;
	DELIMITER_CHARACTER STRING;
	COLUMN_DEFINITIONS ARRAY;    
    UPDATE_DATA_FEED_FILE STRING;
    INSERT_DATA_FEED_FILE STRING;
    UPDATE_COPY_COMMAND_DATA_FEED_FILE STRING;
    FILE_STORAGE_LOCATION STRING;
	DEFAULT_CSV_FILE_FORMAT := ''DATAHUB.PIPELINE_METADATA.CSV_FILE_FORMAT'';
	DEFAULT_FIXED_LENGTH_FILE_FORMAT := ''DATAHUB.PIPELINE_METADATA.FIXED_LENGTH_FILE_FORMAT'';
    SINGLE_QUOTE := '''''''';
BEGIN
	SELECT
			STG_DATABASE_NAME||''.''||STG_SCHEMA_NAME||''.''||STG_TABLE_NAME,
			FILE_FORMAT,
			DELIMITER_CHARACTER,
            FILE_STORAGE_LOCATION_TEXT,
		INTO
			STAGE_TABLE_DETAIL,
			FILE_FORMAT,
			DELIMITER_CHARACTER,
            FILE_STORAGE_LOCATION
		FROM  DATAHUB.PIPELINE_METADATA.DATA_FEED_FILE_INVENTORY 
	WHERE FILE_ID= :FILE_ID AND ACTIVE_FLG=''Y'' ;
	
	COPY_COMMAND := ''COPY INTO '' || STAGE_TABLE_DETAIL || '' FROM (SELECT '';
	
	SELECT
		ARRAY_AGG(
			OBJECT_CONSTRUCT(
				''COLUMN_SEQUENCE_NUMBER'',
				COLUMN_SEQUENCE_NUMBER,
				''COLUMN_START_POSITION_NUMBER'',
				COLUMN_START_POSITION_NUMBER,
				''COLUMN_END_POSITION_NUMBER'',
				COLUMN_END_POSITION_NUMBER
			)
		) INTO COLUMN_DEFINITIONS
	FROM
		INGESTION_TABLE_SCHEMA
	WHERE FILE_ID=:FILE_ID;
	
	IF (UPPER(FILE_FORMAT) = ''CSV'') THEN
		FOR J IN 0 TO ARRAY_SIZE(COLUMN_DEFINITIONS) -1
		DO
			COPY_COMMAND := COPY_COMMAND || ''$'' || COLUMN_DEFINITIONS[J].COLUMN_SEQUENCE_NUMBER || '','';
		END FOR;
    ELSEIF (UPPER(FILE_FORMAT) = ''FIXED_LENGTH'') THEN
        FOR J IN 0 TO ARRAY_SIZE(COLUMN_DEFINITIONS) -1
		DO
			COPY_COMMAND := COPY_COMMAND || ''SUBSTRING($1,'' || COLUMN_DEFINITIONS[J].COLUMN_START_POSITION_NUMBER || '','' || COLUMN_DEFINITIONS[J].COLUMN_END_POSITION_NUMBER || ''),'';            
		END FOR;        
	END IF;
	
    COPY_COMMAND := COPY_COMMAND || ''(PIPELINE_RUN_ID),METADATA$FILE_ROW_NUMBER FROM   @DATAHUB.PIPELINE_METADATA.DATAHUB_AZURE_STORAGE_STAGE/'' || FILE_STORAGE_LOCATION || ''/(source)/(file_name) '';

    

    IF(:ADDITIONAL_WHERE_CONDITIONS IS NOT NULL OR TRIM(:ADDITIONAL_WHERE_CONDITIONS) != '''')THEN
        COPY_COMMAND := COPY_COMMAND || ADDITIONAL_WHERE_CONDITIONS;
    END IF;

    IF(:FILE_FORMAT_NAME IS NOT NULL AND TRIM(:FILE_FORMAT_NAME) != '''')THEN
        COPY_COMMAND := COPY_COMMAND || '' ) FILE_FORMAT = (FORMAT_NAME ='' || :FILE_FORMAT_NAME;
    ELSEIF (UPPER(FILE_FORMAT) = ''CSV'') THEN
        COPY_COMMAND := COPY_COMMAND || '' ) FILE_FORMAT = (FORMAT_NAME ='' || DEFAULT_CSV_FILE_FORMAT;
    ELSEIF (UPPER(FILE_FORMAT) = ''FIXED_LENGTH'') THEN
        COPY_COMMAND := COPY_COMMAND || '' ) FILE_FORMAT = (FORMAT_NAME ='' || DEFAULT_FIXED_LENGTH_FILE_FORMAT;
    END IF;
    
    IF (:SKIP_HEADER IS NOT NULL AND TRIM(:SKIP_HEADER) = ''Y'') THEN
        COPY_COMMAND := COPY_COMMAND || '' SKIP_HEADER=1 '';
    END IF;

    IF (DELIMITER_CHARACTER IS NOT NULL AND TRIM(DELIMITER_CHARACTER) != '''')THEN
        COPY_COMMAND := COPY_COMMAND || ''FIELD_DELIMITER='' || SINGLE_QUOTE || DELIMITER_CHARACTER || SINGLE_QUOTE;
    END IF;

    COPY_COMMAND := COPY_COMMAND || '') FORCE = TRUE ON_ERROR=CONTINUE;'';

    INSERT INTO DATAHUB.PIPELINE_METADATA.DATA_FEED_FILE_INVENTORY_HISTORY  
    (SELECT * FROM DATA_FEED_FILE_INVENTORY WHERE FILE_ID=:FILE_ID AND ACTIVE_FLG=''Y'');

    UPDATE DATA_FEED_FILE_INVENTORY SET COPY_COMMAND_TEXT=:COPY_COMMAND,UPDATED_TS=CURRENT_TIMESTAMP WHERE FILE_ID=:FILE_ID;
        
    RETURN ''PLEASE VALIDATE COPY COMMAND TEXT IN DATA_FEED_FILE_INVENTORY FOR FILE_ID='' || FILE_ID || '' AND ACTIVE_FLAG=Y '';
   
END';