CREATE OR REPLACE PROCEDURE DATAHUB.PIPELINE_METADATA.SP_PIPELINE_TASK_AUDIT_LOG("PIPELINE_RUN_ID" VARCHAR, "TASK_ID" VARCHAR, "TASK_NAME" VARCHAR, "START_TIME" TIMESTAMP_NTZ(9), "END_TIME" TIMESTAMP_NTZ(9), "EXECUTING_CODE" VARCHAR, "EXECUTING_RESULT" VARCHAR, "ERROR_TEXT" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'BEGIN
INSERT INTO DATAHUB.PIPELINE_METADATA.PIPELINE_TASK_AUDIT_LOG VALUES
(:PIPELINE_RUN_ID,:TASK_ID,:TASK_NAME,
:START_TIME,:END_TIME,:EXECUTING_CODE,:EXECUTING_RESULT,:ERROR_TEXT);
END';