CREATE OR REPLACE PROCEDURE DATAHUB.STAGING.SP_AZURE_TO_SNOWFLAKE_DATA_LOAD_PRE_VALIDATION("I_PIPELINE_NAME" VARCHAR(100), "I_PIPELINE_RUN_ID" VARCHAR(100), "I_SOURCE_OF_DATA" VARCHAR(100), "I_FILE_NAME" VARCHAR(300))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'DECLARE 
 FILE_DETAIL_AVAILABLE NUMBER;
 FILEID NUMBER;
 FILENAME VARCHAR;
 MULTILINE_FLG VARCHAR;
 COLUMN_COUNT NUMBER;
 FIXED_LINE_LENGTH NUMBER;
 ERROR_MSG VARCHAR(250);
 FILEFORMAT VARCHAR(30);
 REC_LENGTH NUMBER;
 COPY_COMMAND VARCHAR;
 STG_TABLE VARCHAR;
 TARGET_TABLE VARCHAR;
 FILE_PATH VARCHAR;
 LOAD_TYPE VARCHAR;
 SOURCE_SYSCODE VARCHAR;
 SUBJECT_AREACODE VARCHAR;
 START_TIME TIMESTAMP;
 TASK_NUMBER NUMBER :=0;
 PRIMARY_KEY_COLUMNS VARCHAR;
 ERROR_LOG VARCHAR:=''SELECT * FROM PIPELINE_TASK_AUDIT_LOG WHERE PIPELINE_RUN_ID= ''''''||:I_PIPELINE_RUN_ID||''''''  ORDER BY START_TIME DESC'';
  FILE_DETAILS_NOT_AVAILABLE EXCEPTION (-20002, ''file details are not available in DATA FEED FILE INVENTORY'');
  PRIMARY_KEY_COLUMNS_NOT_FOUND EXCEPTION (-20003, ''Primary key columns are not defined for this table.Please update'');
  FIXED_LINE_LENGTH_NOT_MATCHING EXCEPTION (-20004, ''FIXED_LENGTH_FILE count is not matching between DATA FEED FILE INVENTORY and source file'');
  LOAD_TYPE_NOT_FOUND EXCEPTION (-20005, ''Load type is neither full load not incremental load'');
  
BEGIN
SELECT 
FILE_ID,
FILE_NAME,
MULTI_LINE_FLG,
NUMBER_OF_COLUMNS_COUNT,
RECORD_FORMAT_LENGTH_NUMBER,
FILE_FORMAT,
COPY_COMMAND_TEXT,
FILE_STORAGE_LOCATION_TEXT,
STG_TABLE_NAME,
TARGET_TABLE_NAME,
FULL_LOAD_FLG,
SOURCE_SYS_CODE,
SUBJECT_AREA_CODE,
SOURCE_PRIMARY_KEY
INTO 
FILEID,
FILENAME,
MULTILINE_FLG,
COLUMN_COUNT,
FIXED_LINE_LENGTH,
FILEFORMAT,
COPY_COMMAND,
FILE_PATH,
STG_TABLE,
TARGET_TABLE,
LOAD_TYPE,
SOURCE_SYSCODE,
SUBJECT_AREACODE,
PRIMARY_KEY_COLUMNS
FROM  DATAHUB.PIPELINE_METADATA.TEMP_DATA_FEED_FILE_INVENTORY;

IF (FILENAME IS NULL) THEN
    RAISE FILE_DETAILS_NOT_AVAILABLE;
END IF;

IF (LOAD_TYPE <> ''INCREMENTAL'' AND  LOAD_TYPE <> ''FULL_LOAD'') THEN
    RAISE LOAD_TYPE_NOT_FOUND;
END IF;
    
IF (LOAD_TYPE = ''INCREMENTAL'') THEN
	IF (PRIMARY_KEY_COLUMNS IS NULL) THEN
		RAISE PRIMARY_KEY_COLUMNS_NOT_FOUND;
	END IF;
END IF;

IF (FILEFORMAT=''FIXED_LENGTH'') THEN

SELECT  LENGTH($1) INTO REC_LENGTH FROM @DATAHUB.PIPELINE_METADATA.DATAHUB_AZURE_STORAGE_STAGE/input/nfs/oltp_rep_test_data_2.csv qualify row_number() over (order by null)=2;
    IF (FIXED_LINE_LENGTH<>REC_LENGTH) THEN
        RAISE FIXED_LINE_LENGTH_NOT_MATCHING ;
    END IF;
END IF;

EXCEPTION
                WHEN FILE_DETAILS_NOT_AVAILABLE THEN
                RAISE;
                WHEN PRIMARY_KEY_COLUMNS_NOT_FOUND THEN
                RAISE;
                WHEN FIXED_LINE_LENGTH_NOT_MATCHING THEN
                RAISE;
                WHEN FIXED_LINE_LENGTH_NOT_MATCHING THEN
                RAISE;
                WHEN LOAD_TYPE_NOT_FOUND THEN
                RAISE;
END';